/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sandeep.s (https://sketchfab.com/sandeep.s)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-bird-eb843194e06d429ebef7dd4aa7e265c1
Title: Flying Bird
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { observer } from "mobx-react-lite";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { generateUUID } from "three/src/math/MathUtils";
import { randomnumber } from "../utils/mathUtils";

const Model = observer(({ x, y, rotation }) => {
  const group = useRef();
  const { nodes, materials, animations, scene } = useGLTF("/scene.gltf");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && names.length > 0) {
      actions[names[0]].reset().play();
    }
  }, [actions, names]);

  const scale = 0.3;

  return (
    <group
      ref={group}
      position={[x, y, 0]}
      scale={[scale, scale, scale]}
      dispose={null}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[0, Math.PI / 2, -rotation]}>
          <group
            name="b41216c5de024b378dcea87d8b695888fbx"
            rotation={[3.15, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="FlyingBird"
                  position={[-0.00332676, 0.07887249, 0.07397553]}
                  rotation={[2.92222921, -2, 3.13351321]}
                  scale={0.1}
                >
                  <group
                    name="Bird"
                    position={[0.06367167, 0.14620991, 0.58744365]}
                    scale={0.10409986}
                  >
                    <mesh
                      name="Bird_roll_env_07lambert10_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Bird_roll_env_07lambert10_0.geometry}
                      material={materials.roll_env_07lambert10}
                    />
                  </group>
                  <group
                    name="Bird_RW"
                    position={[-0.05687793, 0.19607745, 0.3489103]}
                    rotation={[-0.06631407, -0.05093514, 0.02469667]}
                    scale={0.10409986}
                  >
                    <mesh
                      name="Bird_RW_roll_env_07fishMaterialSG1_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Bird_RW_roll_env_07fishMaterialSG1_0.geometry
                      }
                      material={materials.roll_env_07fishMaterialSG1}
                    />
                  </group>
                  <group
                    name="Bird_LW"
                    position={[-0.05687793, 0.19607745, 0.3489103]}
                    rotation={[-0.08967373, -0.04575813, -3.10526337]}
                    scale={0.10409986}
                  >
                    <mesh
                      name="Bird_LW_roll_env_07fishMaterialSG1_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Bird_LW_roll_env_07fishMaterialSG1_0.geometry
                      }
                      material={materials.roll_env_07fishMaterialSG1}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/scene.gltf");

export default Model;
